proxies:
proxy-groups:
  - name: "LLYCORIS"
    type: select
    proxies:
      - LOADBALANCE
      - BEST PING
      - FALLBACK
    use:
      - "provide"
  - name: "LOADBALANCE"
    type: load-balance
    strategy: round-robin
    disable-udp: false
    url: http://www.gstatic.com/generate_204
    interval: 1
    lazy: false
    use:
      - "provide"
  - name: "BEST PING"
    type: url-test
    disable-udp: false
    url: http://cp.cloudflare.com/generate_204
    interval: 1
    tolerance: 150
    lazy: false
    use:
      - "provide"
  - name: "FALLBACK"
    type: fallback
    disable-udp: false
    interval: 1
    lazy: false
    use:
      - "provide'            
proxy-providers:
  "provide":
    type: file
    url: "https://raw.githubusercontent.com/Gretong4life/configpribadiCFM/main/proxy_provider/akun.yaml"
    path: ./proxy_provider/akun.yaml
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 1
      lazy: false
rules:
   - DST-PORT,7895,REJECT
   - DST-PORT,7892,REJECT
   - DST-PORT,7895,REJECT
   - DST-PORT,7892,REJECT
   - DST-PORT,7895,REJECT
   - DST-PORT,7892,REJECT
   - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
   - IP-CIDR,127.0.0.1/32,REJECT,no-resolve
   - IP-CIDR6,::1/128,REJECT,no-resolve
   - MATCH,LLYCORIS
